/*
* Generated by XIV.Core.Utils.ClassGenerator
*/
using UnityEngine;

public static class PhysicsConstants
{
	// Members
	public const string Default = "Default";
	public static readonly int DefaultLayer = LayerMask.NameToLayer("Default");
	public const string TransparentFX = "TransparentFX";
	public static readonly int TransparentFXLayer = LayerMask.NameToLayer("TransparentFX");
	public const string Ignore_Raycast = "Ignore Raycast";
	public static readonly int Ignore_RaycastLayer = LayerMask.NameToLayer("Ignore Raycast");
	public const string Water = "Water";
	public static readonly int WaterLayer = LayerMask.NameToLayer("Water");
	public const string UI = "UI";
	public static readonly int UILayer = LayerMask.NameToLayer("UI");
	public const string Node = "Node";
	public static readonly int NodeLayer = LayerMask.NameToLayer("Node");
	public static readonly string[] All = new string[]
	{
		Default,
		TransparentFX,
		Ignore_Raycast,
		Water,
		UI,
		Node,
	};
	
} // class PhysicsConstants
